//! Product-neutral browser-suite navigation contract.
//!
//! Products own their routes and domain navigation. A deployment may expose one
//! trusted hub destination so separately delivered consoles can return to the
//! suite without learning account, tenant, billing, or product topology.

use serde::{Deserialize, Serialize};

/// Same-origin endpoint serving [`SuiteNavigation`].
pub const SUITE_NAVIGATION_PATH: &str = "/.well-known/awaken-suite-navigation";

/// Query parameter used to carry an untrusted absolute product URL back to a
/// composing suite hub. The hub remains responsible for validating it against
/// authenticated product coordinates before issuing any launch capability.
pub const SUITE_CONTINUATION_PARAMETER: &str = "continue";

/// Optional deployment-owned navigation out of one product console.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize, Serialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(deny_unknown_fields)]
pub struct SuiteNavigation {
    /// Exact trusted URL of the suite hub. `None` keeps a standalone product
    /// self-contained and must not be replaced by hostname inference.
    pub hub_url: Option<String>,
}

/// Render the product-neutral TypeScript decision used by browser consumers.
///
/// This is generated into product repositories so the two independently built
/// consoles do not maintain parallel implementations. It has no redirect side
/// effect and treats the continuation as opaque, untrusted browser state.
pub fn suite_navigation_browser_module() -> String {
    format!(
        r#"// Generated by `awaken-foundation xtask suite-navigation-browser`; do not edit.

export interface SuiteNavigation {{
  readonly hub_url: string | null;
}}

export type HostedSessionEntry =
  | {{ readonly kind: "continue" }}
  | {{ readonly kind: "redirect"; readonly url: string }};

/**
 * Hosted-entry cause/effect table:
 * exact hub + absent bearer -> exact hub with one untrusted continuation;
 * absent hub or present bearer -> continue in the current product.
 */
export function hostedSessionEntry(
  navigation: SuiteNavigation,
  sessionBearer: string,
  currentUrl: string,
): HostedSessionEntry {{
  if (!navigation.hub_url || sessionBearer) return {{ kind: "continue" }};
  const hub = new URL(navigation.hub_url);
  hub.searchParams.set("{SUITE_CONTINUATION_PARAMETER}", currentUrl);
  return {{ kind: "redirect", url: hub.href }};
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Cause-effect graph:
    /// deployment hub configured -> serialize exact opaque destination;
    /// deployment hub absent -> serialize an explicit null capability;
    /// extra wire field -> reject instead of silently accepting contract drift.
    ///
    /// Decision table:
    /// | rule | hub input | unknown field | effect |
    /// | R1 | exact URL | no | exact round trip |
    /// | R2 | absent | no | explicit standalone projection |
    /// | R3 | any | yes | decode failure |
    #[test]
    fn suite_navigation_wire_is_exact_and_fail_closed() {
        let hosted = SuiteNavigation {
            hub_url: Some("https://cloud.example/products".to_owned()),
        };
        let encoded = serde_json::to_string(&hosted).expect("serialize hosted navigation");
        assert_eq!(
            serde_json::from_str::<SuiteNavigation>(&encoded).unwrap(),
            hosted,
            "R1"
        );

        let standalone = serde_json::to_value(SuiteNavigation::default()).unwrap();
        assert_eq!(standalone, serde_json::json!({ "hub_url": null }), "R2");

        assert!(
            serde_json::from_value::<SuiteNavigation>(serde_json::json!({
                "hub_url": null,
                "tenant_id": "must-not-cross-this-contract"
            }))
            .is_err(),
            "R3"
        );
    }

    /// Browser-module cause/effect coverage:
    /// C1 is an exact hub, C2 is a present canonical bearer, and C3 is the
    /// current absolute URL. R1(C1,!C2) encodes C3 once under the shared key;
    /// R2(!C1,*) and R3(C1,C2) continue without a redirect. Product Vitest
    /// suites execute all rows from the generated module.
    #[test]
    fn browser_module_has_one_continuation_contract_and_no_side_effect() {
        let module = suite_navigation_browser_module();
        assert!(module.contains("if (!navigation.hub_url || sessionBearer)"));
        assert!(module.contains("hub.searchParams.set(\"continue\", currentUrl)"));
        assert!(!module.contains("window.location"));
        assert!(!module.contains("fetch("));
        assert!(!module.contains("sessionStorage"));
    }
}
