use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use thiserror::Error;

/// Header used by HTTP adapters to propagate request correlation ids.
pub const REQUEST_ID_HEADER: &str = "x-request-id";

/// Content type for RFC 9457 Problem Details JSON responses.
pub const PROBLEM_JSON_CONTENT_TYPE: &str = "application/problem+json";

/// Header required by AI SDK UI message stream compatible data streams.
pub const AI_SDK_UI_MESSAGE_STREAM_HEADER: &str = "x-vercel-ai-ui-message-stream";

/// Header value for AI SDK UI message stream protocol v1.
pub const AI_SDK_UI_MESSAGE_STREAM_V1: &str = "v1";

/// RFC 9457 Problem Details with stable application extension members.
///
/// The standard members (`type`, `title`, `status`, `detail`, `instance`) make
/// the payload compatible with HTTP tooling. Extension members (`code`,
/// `request_id`, `details`, `errors`) carry product-specific machine context.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct ApiError {
    /// URI reference identifying the problem type. Use `about:blank` only for
    /// generic HTTP status problems; application errors should use stable URNs
    /// or URLs.
    #[serde(rename = "type")]
    pub problem_type: ProblemType,
    /// Stable human-readable summary for this problem type.
    pub title: String,
    /// HTTP status code generated by the origin server.
    pub status: u16,
    /// Request-specific human-readable explanation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// URI reference identifying this occurrence, when available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Stable application error code. Clients may branch on this.
    pub code: String,
    /// Request correlation id echoed through [`REQUEST_ID_HEADER`].
    pub request_id: String,
    /// Type-specific structured metadata.
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub details: Value,
    /// Field/query/header violations for validation-style problems.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub errors: Vec<FieldError>,
}

impl ApiError {
    /// Build a Problem Details error with a stable application code.
    #[must_use]
    pub fn new(
        status: u16,
        code: impl Into<String>,
        title: impl Into<String>,
        detail: impl Into<String>,
        request_id: impl Into<String>,
    ) -> Self {
        let code = code.into();
        Self {
            problem_type: problem_type_for_code(&code),
            title: title.into(),
            status,
            detail: Some(detail.into()),
            instance: None,
            code,
            request_id: request_id.into(),
            details: Value::Null,
            errors: Vec::new(),
        }
    }

    /// Build a validation failure with one field error.
    #[must_use]
    pub fn validation(
        path: impl Into<String>,
        code: impl Into<String>,
        message: impl Into<String>,
        request_id: impl Into<String>,
    ) -> Self {
        let message = message.into();
        Self::new(
            422,
            "validation_failed",
            "Validation failed",
            message.clone(),
            request_id,
        )
        .with_error(FieldError::new(path, code).with_message(message))
    }

    /// Override the problem type URI.
    #[must_use]
    pub fn with_problem_type(mut self, problem_type: ProblemType) -> Self {
        self.problem_type = problem_type;
        self
    }

    /// Parse and override the problem type URI reference.
    ///
    /// This is useful at adapter boundaries that load type URIs from generated
    /// route metadata.
    pub fn try_with_problem_type(
        mut self,
        problem_type: impl AsRef<str>,
    ) -> Result<Self, ProblemTypeError> {
        self.problem_type = ProblemType::parse(problem_type)?;
        Ok(self)
    }

    /// Attach an occurrence URI.
    #[must_use]
    pub fn with_instance(mut self, instance: impl Into<String>) -> Self {
        self.instance = Some(instance.into());
        self
    }

    /// Attach structured metadata.
    #[must_use]
    pub fn with_details(mut self, details: Value) -> Self {
        self.details = details;
        self
    }

    /// Add one validation/detail error.
    #[must_use]
    pub fn with_error(mut self, error: FieldError) -> Self {
        self.errors.push(error);
        self
    }

    /// Project this envelope into the AI SDK UI data-stream error part.
    ///
    /// The AI SDK error part only carries display text. Emit a companion
    /// `data-*` part if the full structured envelope must also be preserved in
    /// a stream.
    #[must_use]
    pub fn to_ai_sdk_error_part(&self) -> AiSdkErrorPart {
        AiSdkErrorPart {
            part_type: "error".to_string(),
            error_text: self.display_message(),
        }
    }

    /// Project this envelope into a typed AI SDK custom data part.
    #[must_use]
    pub fn to_ai_sdk_data_part(&self, suffix: impl Into<String>) -> AiSdkDataPart<ApiError> {
        AiSdkDataPart {
            part_type: format!("data-{}", suffix.into()),
            data: self.clone(),
        }
    }

    /// Project this envelope into an AG-UI `RUN_ERROR` event.
    #[must_use]
    pub fn to_ag_ui_run_error(&self) -> AgUiRunErrorEvent {
        AgUiRunErrorEvent {
            event_type: "RUN_ERROR".to_string(),
            message: self.display_message(),
            code: Some(self.code.clone()),
            timestamp: None,
            raw_event: Some(json!(self)),
        }
    }

    fn display_message(&self) -> String {
        self.detail
            .clone()
            .filter(|detail| !detail.trim().is_empty())
            .unwrap_or_else(|| self.title.clone())
    }
}

fn problem_type_for_code(code: &str) -> ProblemType {
    ProblemType::urn("api-contract", "problem", code)
}

/// RFC 9457 problem type URI reference.
///
/// `type` is not an arbitrary application string. It should be a stable URI
/// reference such as `https://api.example.com/problems/validation-failed`, a
/// product-owned URN, or `about:blank` for generic HTTP status problems. The
/// short branchable application code belongs in [`ApiError::code`].
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct ProblemType(String);

impl ProblemType {
    /// Generic RFC 9457 problem type for plain HTTP status errors.
    pub const ABOUT_BLANK: &'static str = "about:blank";

    /// Parse a URI reference used as a Problem Details `type`.
    pub fn parse(value: impl AsRef<str>) -> Result<Self, ProblemTypeError> {
        let value = value.as_ref();
        if value.is_empty() {
            return Err(ProblemTypeError::Empty);
        }
        if value
            .chars()
            .any(|ch| ch.is_ascii_control() || ch.is_whitespace())
        {
            return Err(ProblemTypeError::InvalidUriReference(value.to_string()));
        }
        if value != Self::ABOUT_BLANK && !value.contains(':') && !value.starts_with('/') {
            return Err(ProblemTypeError::ExpectedUriReference(value.to_string()));
        }
        Ok(Self(value.to_string()))
    }

    /// Build a namespaced URN problem type.
    ///
    /// The segments are normalized to lowercase ASCII with separators converted
    /// to `-`, so application codes can keep using snake_case.
    #[must_use]
    pub fn urn(namespace: &str, category: &str, code: &str) -> Self {
        Self(format!(
            "urn:{}:{}:{}",
            normalize_urn_segment(namespace),
            normalize_urn_segment(category),
            normalize_urn_segment(code)
        ))
    }

    /// Build a URL-style problem type after lightweight URI-reference checks.
    pub fn url(value: impl AsRef<str>) -> Result<Self, ProblemTypeError> {
        let problem_type = Self::parse(value)?;
        let value = problem_type.as_str();
        if !(value.starts_with("https://") || value.starts_with("http://")) {
            return Err(ProblemTypeError::ExpectedUrl(value.to_string()));
        }
        Ok(problem_type)
    }

    /// Build `about:blank`.
    #[must_use]
    pub fn about_blank() -> Self {
        Self(Self::ABOUT_BLANK.to_string())
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ProblemType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl FromStr for ProblemType {
    type Err = ProblemTypeError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::parse(value)
    }
}

impl TryFrom<String> for ProblemType {
    type Error = ProblemTypeError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(value)
    }
}

impl From<ProblemType> for String {
    fn from(problem_type: ProblemType) -> Self {
        problem_type.0
    }
}

/// Invalid RFC 9457 problem type URI reference.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum ProblemTypeError {
    #[error("problem type URI reference must not be empty")]
    Empty,
    #[error("problem type must be a URI reference without whitespace or control characters: {0}")]
    InvalidUriReference(String),
    #[error("problem type must be about:blank, an absolute URI/URN, or an absolute path: {0}")]
    ExpectedUriReference(String),
    #[error("problem type URL must start with http:// or https://: {0}")]
    ExpectedUrl(String),
}

fn normalize_urn_segment(value: &str) -> String {
    let normalized: String = value
        .chars()
        .map(|ch| match ch {
            'A'..='Z' => ch.to_ascii_lowercase(),
            'a'..='z' | '0'..='9' => ch,
            '-' | '_' | '.' => '-',
            _ => '-',
        })
        .collect();
    normalized.trim_matches('-').to_string()
}

/// Structured validation error for one request field, query parameter, or
/// header. This borrows JSON:API's source idea while keeping a compact shape.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct FieldError {
    pub path: String,
    pub code: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<ErrorSource>,
}

impl FieldError {
    #[must_use]
    pub fn new(path: impl Into<String>, code: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            code: code.into(),
            message: None,
            source: None,
        }
    }

    #[must_use]
    pub fn with_message(mut self, message: impl Into<String>) -> Self {
        self.message = Some(message.into());
        self
    }

    #[must_use]
    pub fn with_source(mut self, source: ErrorSource) -> Self {
        self.source = Some(source);
        self
    }
}

/// Where a field error came from.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct ErrorSource {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pointer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameter: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub header: Option<String>,
}

impl ErrorSource {
    #[must_use]
    pub fn pointer(pointer: impl Into<String>) -> Self {
        Self {
            pointer: Some(pointer.into()),
            parameter: None,
            header: None,
        }
    }

    #[must_use]
    pub fn parameter(parameter: impl Into<String>) -> Self {
        Self {
            pointer: None,
            parameter: Some(parameter.into()),
            header: None,
        }
    }

    #[must_use]
    pub fn header(header: impl Into<String>) -> Self {
        Self {
            pointer: None,
            parameter: None,
            header: Some(header.into()),
        }
    }
}

/// AI SDK UI data-stream error part.
///
/// Wire shape: `{ "type": "error", "errorText": "..." }`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AiSdkErrorPart {
    #[serde(rename = "type")]
    pub part_type: String,
    #[serde(rename = "errorText")]
    pub error_text: String,
}

/// AI SDK UI data-stream custom data part.
///
/// The `type` field should follow the `data-*` convention, for example
/// `data-api-error`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AiSdkDataPart<T> {
    #[serde(rename = "type")]
    pub part_type: String,
    pub data: T,
}

/// AG-UI run error lifecycle event.
///
/// Wire shape: `{ "type": "RUN_ERROR", "message": "...", "code": "..." }`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AgUiRunErrorEvent {
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<u64>,
    #[serde(rename = "rawEvent", default, skip_serializing_if = "Option::is_none")]
    pub raw_event: Option<Value>,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builds_problem_details_envelope() {
        let error = ApiError::new(404, "not_found", "Not found", "missing", "req_1")
            .with_details(json!({ "id": "a" }))
            .with_instance("/requests/req_1");
        assert_eq!(
            error.problem_type.as_str(),
            "urn:api-contract:problem:not-found"
        );
        assert_eq!(error.title, "Not found");
        assert_eq!(error.status, 404);
        assert_eq!(error.detail.as_deref(), Some("missing"));
        assert_eq!(error.details["id"], "a");
        assert_eq!(error.request_id, "req_1");
        assert_eq!(error.instance.as_deref(), Some("/requests/req_1"));
    }

    #[test]
    fn serializes_problem_details_shape() {
        let error = ApiError::new(403, "forbidden", "Forbidden", "not authorized", "req_2");
        let value = serde_json::to_value(error).unwrap();
        assert_eq!(value["type"], "urn:api-contract:problem:forbidden");
        assert_eq!(value["title"], "Forbidden");
        assert_eq!(value["status"], 403);
        assert_eq!(value["detail"], "not authorized");
        assert_eq!(value["code"], "forbidden");
        assert_eq!(value["request_id"], "req_2");
        assert!(value.get("error").is_none());
    }

    #[test]
    fn builds_validation_errors_with_source() {
        let error =
            ApiError::validation("filter[status]", "unsupported_field", "bad filter", "req_3")
                .with_error(
                    FieldError::new("body.name", "required")
                        .with_message("name is required")
                        .with_source(ErrorSource::pointer("/name")),
                );
        assert_eq!(error.code, "validation_failed");
        assert_eq!(error.status, 422);
        assert_eq!(error.errors[0].path, "filter[status]");
        assert_eq!(error.errors[0].code, "unsupported_field");
        assert_eq!(
            error.errors[1].source.as_ref().unwrap().pointer.as_deref(),
            Some("/name")
        );
    }

    #[test]
    fn parses_and_serializes_problem_type_as_string() {
        let problem_type =
            ProblemType::url("https://api.example.test/problems/validation-failed").unwrap();
        let error = ApiError::new(
            422,
            "validation_failed",
            "Validation failed",
            "bad",
            "req_7",
        )
        .with_problem_type(problem_type);

        let value = serde_json::to_value(&error).unwrap();
        assert_eq!(
            value["type"],
            "https://api.example.test/problems/validation-failed"
        );

        let parsed: ApiError = serde_json::from_value(value).unwrap();
        assert_eq!(
            parsed.problem_type.as_str(),
            "https://api.example.test/problems/validation-failed"
        );
    }

    #[test]
    fn rejects_invalid_problem_type_uri_reference() {
        assert_eq!(ProblemType::parse(""), Err(ProblemTypeError::Empty));
        assert!(matches!(
            ProblemType::parse("validation failed"),
            Err(ProblemTypeError::InvalidUriReference(_))
        ));
        assert!(matches!(
            ProblemType::parse("validation_failed"),
            Err(ProblemTypeError::ExpectedUriReference(_))
        ));
        assert!(matches!(
            ProblemType::url("urn:api-contract:problem:validation-failed"),
            Err(ProblemTypeError::ExpectedUrl(_))
        ));
        assert!(
            serde_json::from_value::<ApiError>(json!({
                "type": "",
                "title": "Bad request",
                "status": 400,
                "code": "bad_request",
                "request_id": "req_8"
            }))
            .is_err()
        );
    }

    #[test]
    fn projects_to_ai_sdk_error_part() {
        let error = ApiError::new(
            503,
            "dependency_unavailable",
            "Dependency unavailable",
            "model unavailable",
            "req_4",
        );
        let part = error.to_ai_sdk_error_part();
        assert_eq!(part.part_type, "error");
        assert_eq!(part.error_text, "model unavailable");
        assert_eq!(
            serde_json::to_value(part).unwrap(),
            json!({ "type": "error", "errorText": "model unavailable" })
        );
    }

    #[test]
    fn projects_to_ai_sdk_data_part() {
        let error = ApiError::new(
            403,
            "forbidden",
            "Forbidden",
            "principal is not authorized",
            "req_5",
        );
        let part = error.to_ai_sdk_data_part("api-error");
        assert_eq!(part.part_type, "data-api-error");
        assert_eq!(part.data.code, "forbidden");
    }

    #[test]
    fn projects_to_ag_ui_run_error() {
        let error = ApiError::new(
            422,
            "validation_failed",
            "Validation failed",
            "invalid input",
            "req_6",
        );
        let event = error.to_ag_ui_run_error();
        assert_eq!(event.event_type, "RUN_ERROR");
        assert_eq!(event.message, "invalid input");
        assert_eq!(event.code.as_deref(), Some("validation_failed"));
        assert!(event.raw_event.is_some());
    }
}
